// object mapping of entity types to player choice options
const entityMapping = {
    NAME: 'Name',
    OCCUPATION: 'Occupation',
    ANIMAL: 'Animal',
    LOCATION: 'Location (non-geographic)',
    ROOM: 'Room in the House',
    RESTAURANT: 'Restaurant',
    STORE: 'Store',
    CITY: 'City',
    COUNTRY: 'Country',
    ORGANIZATION: 'Type of Organization',
    BAND: 'Band',
    COMPANY: 'Company',
    POLITICAL_PARTY: 'Political Party',
    UNIVERSITY: 'University',
    SPORTS_TEAM: 'Sports Team',
    EVENT: 'Event',
    WORK_OF_ART: 'Type of Artwork',
    ALBUM: 'Album',
    MOVIE: 'Movie',
    NOVEL: 'Novel',
    POEM: 'Poem',
    PAINTING: 'Painting',
    CONSUMER_GOOD: 'Consumer Good',
    VEHICLE: 'Vehicle',
    FOOD: 'Food/Drink',
    INSTRUMENT: 'Instrument',
    TOOL: 'Tool',
    TOY: 'Toy',
    WEAPON: 'Weapon',
    CLOTHING: 'Clothing',
    PHONE_NUMBER: 'Phone Number',
    ADDRESS: 'Address',
    DATE: 'Date',
    NUMBER: 'Number',
    PRICE: 'Price',
    ADJ: 'Adjective',        
}

export default entityMapping;